name: Create .env files
author: Arky Asmal
description: Create a .env file in a github runner, from environment variables. Can be used prior to the build step of an application
inputs:
  APP_SECRETS:
    required: true
  PREFIX_FILTER:
    required: false
  ENV_FILE_NAME:
    required: false
  DESTINATION_PATH:
    required: false
  WORKING_DIRECTORY_PATH:
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
