name: "Test Workflow"
on: [push, pull_request]
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Env
      working-directory: ./src
      uses: ./
      with: 
        REACT_APP_SECRETS: ${{toJson(secrets)}}
    - name: List Env file
      run: ls -a
