name: "Test Workflow 4"
on: [push, pull_request]
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    working-directory: ./src
    steps:
    - uses: actions/checkout@v1
    - name: Create Env
      uses: ./
      with: 
        REACT_APP_SECRETS: ${{toJson(secrets)}}
    - name: List Env file
      run: cd src; ls -a